export const ACTION_TYPES = [
	"INCREMENT_BREAK_MINUTES",
	"DECREMENT_BREAK_MINUTES",
	"INCREMENT_SESSION_MINUTES",
	"DECREMENT_SESSION_MINUTES",
	"PLAY",
	"PAUSE",
	"SWITCH_TIMER",
	"DECREMENT_RUNNING_MINUTES",
	"DECREMENT_SECONDS",
	"RESET_ALL"
] as const;
